// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SaveTabs
{
    internal sealed partial class Vsix
    {
        public const string Id = "SaveTabs.cbae93c0-7eb9-4920-b91a-39bacc0e4b61";
        public const string Name = "SaveTabs";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "HP";
        public const string Tags = "";
    }
}
