// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SaveTabs
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SaveTabsString = "4234ab2c-8319-4c88-9241-00cde0494d02";
        public static Guid SaveTabs = new Guid(SaveTabsString);

        public const string guidSaveTabsPackageCmdSetString = "c118074a-aed7-49ed-8b33-d2a42ffa5f1b";
        public static Guid guidSaveTabsPackageCmdSet = new Guid(guidSaveTabsPackageCmdSetString);

        public const string guidImagesString = "0c3df1c5-a3f8-4298-80c6-c84b6027957d";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidSHLMainMenuString = "d309f791-903f-11d0-9efc-00a0c911004f";
        public static Guid guidSHLMainMenu = new Guid(guidSHLMainMenuString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int MyCommand = 0x0100;
        public const int cmdidSaveTabsDialogCommand = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
        public const int IDM_VS_MENU_EXTENSIONS = 0x0091;
    }
}